spring:
  datasource:
    url: jdbc:postgresql://postgres-server:5432/user-management
    driver-class-name: org.postgresql.Driver
    username: adrian
    password: Adrian1999
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL92Dialect
    hibernate:
      ddl-auto: update
  application:
    name: adrian-user-management

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://eureka-server:8761/eureka}