spring:
  datasource:
    url: jdbc:h2:mem:devDb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  application:
    name: adrian-user-management
  h2:
    console:
      enabled: true
      path: /h2-console

eureka:
  client:
    service-url:
      192.168.5.24: http://localhost:8761/eureka
